apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3  # Number of replicas or instances
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: nandagiri25/product_service:latest
        ports:
            - containerPort: 8081